name = "FinalProjectRepo"
uuid = "738d0627-c92e-4bfb-a2c0-9371a9b1b3d4"
authors = ["Mauro Werder <mauro3@runbox.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
